### ISSUE TITLE
Richi!

### ISSUE THREAD

**Issue by esteban-uo** [igl/uber-next#1]
so, nextjs vs gatsbyjs? :)

**Comment by igl** [comment]
Gatsby works like `next export` right? 😄

Where are you you at? Still with otto/something?

**Comment by esteban-uo** [comment]
I think you can do pretty much the same in Gatsby as next. But seems to be the community is more happy with Gatsby. I used Next in some small projects but when I realized that Gatsby exists I started reading more about it, but that was like 2 years ago 😅 

No more otto stuff, are you in hamburg? we should meet! 😄

**Comment by igl** [comment]
yea, bought a flat here. So i am staying a bit longer ;)
Working at the Hafencity close to Baumwall.
